### ISSUE TITLE
ObjectInspector works, Inspector doesn't

### ISSUE THREAD

**Issue by ilbonte** [storybookjs/react-inspector#10]
I have this basic example: 

```
import React from 'react';
import ReactDOM from 'react-dom';
import {ObjectInspector, TableInspector} from 'react-inspector';

// or use the shorthand
import {Inspector} from 'react-inspector';

let data = {
    name: 'Davide',
    age: 23
};

ReactDOM.render(
    <div>
    <Inspector data={data}/>
</div>, document.getElementById('app'));
```

But I get this error:

```
warning.js?8a56:44Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).warning @ warning.js?8a56:44createElement @ ReactElementValidator.js?a599:221(anonymous function) @ index.jsx?283d:15(anonymous function) @ app.js:1045__webpack_require__ @ app.js:556fn @ app.js:87(anonymous function) @ app.js:588__webpack_require__ @ app.js:556(anonymous function) @ app.js:579(anonymous function) @ app.js:582
invariant.js?4599:38Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

But if I use

```
    <ObjectInspector data={data} />
 <TableInspector data={data} />
```

Works just fine! Is there difference between ObjectInspector  and Inspector?
Is ObjectInspector  the old https://github.com/xyc/react-object-inspector?

I'm using 

```
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-inspector": "^1.0.0"
```

With this boilerplate: https://github.com/survivejs/react-boilerplate

If you need I can upload the repo so you can try!

**Comment by xyc** [comment]
Hi @ilbonte , please use 

``` js
import Inspector from 'react-inspector';
```

Inspector is currently default export. Will add it in named exports in the next version.
Difference between ObjectInspector and Inspector is that Inspector will check whether the object is a DOM Node and use DOM Inspector instead. `<ObjectInspector>` functions same as the old https://github.com/xyc/react-object-inspector, except that it supports surfacing non-enumerable properties now.

**Comment by ilbonte** [comment]
Oh ok thank you! Maybe you should update the readme 😉 
EDIT: noticed now that now is up to date
