### ISSUE TITLE
Sorting properties

### ISSUE THREAD

**Issue by bripkens** [storybookjs/react-inspector#12]
It would be great if properties of objects could optionally be sorted by the key. We are using this for dev tools and sometimes we are inspecting larger objects. Having it sorted by key would help us big time.

**Comment by xyc** [comment]
Will add an optional prop like sortObjectKeys in https://github.com/alexkuz/react-json-tree#more-options

**Comment by bripkens** [comment]
thanks @xyc!

**Comment by xyc** [comment]
Resolved in 1.1.0
