### ISSUE TITLE
[Bug] React 17 support

### ISSUE THREAD

**Issue by mtmacdonald** [storybookjs/react-inspector#121]
Hi! Can we please have React 17 support so I don't get this peer dependency warning upon npm install in my React 17 projects. Thanks!

npm WARN react-inspector@5.1.0 requires a peer of react@^16.8.4 but none is installed. You must install peer dependencies yourself.

**Comment by pip8786** [comment]
It seems to be updated in the package.json but not published. Is there any way to get published?

**Comment by jackric** [comment]
Please publish a patch release! I am current required to install deps with `$ npm install --legacy-peer-deps` without this.

**Comment by pd8** [comment]
Hi I was wondering if this version had been released already - I can see the code in your main branch but it doesn't look like a new version has been published yet. This would unblock part of the storybook 6.1 react 17 support for npm 7, so was hoping we'd see a new version soon, I can see @bcomnes merged the change... hello again from https://github.com/reach/router/pull/452 ! I was wondering who manages the releases?

**Comment by kvnwolf** [comment]
This is also causing projects with `npm@>7.x` installs. Is there a chance this could be released soon?

**Comment by siiiiilvio** [comment]
🚢  🙏

**Comment by silltho** [comment]
@ndelangen am i right that this is blocked by https://github.com/reach/router/pull/452? If not is there anything the community could do to get this released?

**Comment by ndelangen** [comment]
@silltho I invited you to the github org, if you could help out getting this repo is a better shape, that'd be amazing.

If you'd like to also publish new version no npm, let's have a quick chat via the storybook discord:
https://discord.gg/js3AjMg6dW

**Comment by bcomnes** [comment]
@ndelangen I reached out on discord to help out. @Hypnosphi is already a contributor and has been helpful to get a bunch of the other packages over the line.  Perhaps consider giving him publishing permissions.  I'm also willing to help with that if nobody else is.

**Comment by bcomnes** [comment]
Ok, I have contribution access and will get a new release out to fix this.

**Comment by thomasboyt** [comment]
Hi, is anything preventing a release of 5.1.1? Currently working around this bug with `npm install --legacy-peer-deps` but rather awkward to make sure that's used everywhere.

**Comment by silltho** [comment]
@thomasboyt you can use a `.npmrc` file in the root of your project with ```legacy-peer-deps=true``` to set the flag.

**Comment by bcomnes** [comment]
Ok react-inspector 5.1.1 supports react 17.  Sorry for the wait.  It looks like reach router is the last thing holding off react 17 support:

https://github.com/reach/router/pull/452
