### ISSUE TITLE
`Name` property does not appear to be rendered

### ISSUE THREAD

**Issue by austinnichols101** [storybookjs/react-inspector#13]
I believe there may be a problem when specifying the `name` property.  

In the following screenshot I have two arrays being displayed, using the following props:

```
<Inspector data={data1} name="Array 1" expandLevel=1 />
<Inspector data={data2} name="Array 2" expandLevel=1 />
```

![image](https://cloud.githubusercontent.com/assets/6962379/16569236/ee4725d8-4201-11e6-8d72-67745807be24.png)

I would expect that the root node would show the value of the name property rather than the first row of the array.

**Comment by austinnichols101** [comment]
Suggest adding a check for name at https://github.com/xyc/react-inspector/blob/master/src/tree-view/TreeView.js#L85

```
          // show name, if specified, for root nodes
          , shouldShowName: depth == 0 && name.length > 0
```

And then rendering the name itself at https://github.com/xyc/react-inspector/blob/master/src/tree-view/TreeNode.js#L64

```
{ shouldShowName ? name : renderedNode }
```

**Comment by xyc** [comment]
Hello @austinnichols101 , I'm working on fixing this. Should be fixed in the next version.

**Comment by xyc** [comment]
Resolved in 1.1.0

**Comment by austinnichols101** [comment]
@xyc : Thanks for the update - I now see the name field being rendered.  However, the data contents are also being rendered.  I think that the data contents should be suppressed if the name field is specified.

![image](https://cloud.githubusercontent.com/assets/6962379/16918773/fed3b708-4cd4-11e6-83ae-a3c2df631cd1.png)

**Comment by xyc** [comment]
Hi @austinnichols101  Thanks for trying it out.
Currently there's no specs on this (in browser devtools) - Default to render data contents since libraries like `react-storybook` depend on this and need the data contents to be rendered.

May I ask the reason that you have specific needs for suppressing the data contents?

Will consider adding customizable `nodeRenderer` (define custom component to render node data) and expose the API in the next version so that we have the freedom to define how the data should be rendered.

**Comment by austinnichols101** [comment]
@xyc

For backwards-compatible behavior with react-object-inspector.  Below is an example of how the name was rendered.

![image](https://cloud.githubusercontent.com/assets/6962379/17193032/2925e3b8-541f-11e6-92f3-ee45192ae10b.png)

```
create = React.create-element
Inspector  = require \react-object-inspector
create Inspector, name: ' VM List' data: vmList ? {})
```

**Comment by ndelangen** [comment]
This is resolved right?
