### ISSUE TITLE
npm install from github fails

### ISSUE THREAD

**Issue by austinnichols101** [storybookjs/react-inspector#15]
When I install using the following command:

`npm install xyc/react-inspector`

The library installs, but I receive errors afterwards:

`Error: Cannot find module 'react-inspector'`

**Comment by xyc** [comment]
Hi @austinnichols101 , github repo doesn't include lib/.
You would need to run `npm run build` if it's installed from github.

**Comment by xyc** [comment]
should be resolved in 1.1.0
