### ISSUE TITLE
Implicit dependency on babel-runtime

### ISSUE THREAD

**Issue by glenjamin** [storybookjs/react-inspector#18]
I tried using this on a project where I hadn't bothered with babel yet, and discovered that the transpilation settings produce `require()` calls to `babel-runtime`, which isn't specified as a dependency.

The two possible solutions that come to mind are switching the compiler options to inline the shims, or to add the dependency.

**Comment by xyc** [comment]
Hi Glen,

Thanks for the suggestions. Fixed in 1.1.1 by adding the dependency.

Reference: https://github.com/xyc/react-inspector/issues/14
