### ISSUE TITLE
React 15 upgrade is now throwing warnings

### ISSUE THREAD

**Issue by cgood92** [storybookjs/react-inspector#25]
Once I upgraded my react project to React 15+ (currently `15.5.4`), I am getting 3 warnings on every page of my storybook, and it's starting to get a little annoying.  I have traced back 2 of the warnings to this npm package.

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

This is because React.PropTypes is now considered deprecated, in favor of using the npm library `prop-types` instead (see the top banner of https://facebook.github.io/react/docs/typechecking-with-proptypes.html).  The conversion is fairly easy and painless.  If I get the time, I'll make the PR myself.  But, this issue would be nice to resolve soon.

This package is a dependency of `@kadira/storybook-addon-actions@^1.0.2` and `@kadira/storybook-ui@^3.10.1`, which are being brought into my project.

Thanks

**Comment by cgood92** [comment]
Here is the related PR: https://github.com/xyc/react-inspector/pull/26

**Comment by ndelangen** [comment]
Storybook maintainer here, Can we help in any way?

**Comment by ndelangen** [comment]
I'm now co-maintaining this package, and will be publishing a new version shortly fixing this.
