### ISSUE TITLE
expandLevel only works for component initialization

### ISSUE THREAD

**Issue by Hurtak** [storybookjs/react-inspector#29]
Hi,

is it possible to set expandLevel programatically after the component has been initialized. The `expandLevel` prop seems to only work on initial expanding.

**Comment by CodyReichert** [comment]
Like this? https://www.webpackbin.com/bins/-KkMqgc8xqC8J1wMD6n2

**Comment by Hurtak** [comment]
My use case is I have buttons that set react-inspector to certain expand level. Unless I am doing something wrong, it seems to be only working for expanding, but not for collapsing.

https://www.webpackbin.com/bins/-KkMxUuKiy5eD5G_-l0d

**Comment by CodyReichert** [comment]
Ah ok, so it looks like it's similar to #16. I haven't dug into that part of the code too much, but I'll try and take a look soon.

**Comment by CodyReichert** [comment]
Actually, I'm gonna go ahead and close this in lieu of #16 -- but please re-open if it's not the same issue!
