### ISSUE TITLE
Why there is nothing on localhost:9001 after run the project?

### ISSUE THREAD

**Issue by BruceConstantine** [storybookjs/react-inspector#44]
As titile。。。

**Comment by ndelangen** [comment]
This is what I get when I run `yarn storybook`:
<img width="477" alt="screen shot 2018-01-23 at 23 25 56" src="https://user-images.githubusercontent.com/3070389/35304147-cac7b962-0094-11e8-8b08-a9fdc4435c65.png">

<img width="1916" alt="screen shot 2018-01-23 at 23 25 16" src="https://user-images.githubusercontent.com/3070389/35304132-b93cb670-0094-11e8-8b4e-0782d208cf9f.png">

Please provide more information on what you're doing, what you're getting, and what you're expecting.

**Comment by xyc** [comment]
Closing - not reproducible
