### ISSUE TITLE
Option to Turn Off Child Summary

### ISSUE THREAD

**Issue by philcockfield** [storybookjs/react-inspector#45]
When an item contains many children, for instance the array shown below:

![image](https://user-images.githubusercontent.com/185555/35534367-30780e64-05a5-11e8-9374-f896beb5668f.png)

It would be nice to have a property that tells the component to how rendering the summary, especially if the item is open, it's repeating data that is on-screen and when the object/array is large, it's very noise on screen.

[is this possible?  If not, can we have it as a feature please? 🍰   It's a very beautiful component you've created.]

**Comment by ndelangen** [comment]
How about not rendering the summery when it's expanded, will that work?

**Comment by philcockfield** [comment]
Yeah. That would be perfect.

**Comment by xyc** [comment]
@philcockfield you can use a custom node renderer. see example here: https://codesandbox.io/s/8485j7llrl

**Comment by CodyReichert** [comment]
Ah right, good solution @xyc - forgot about that feature, but that would be the best way to do it right now.

Also, it would be nice if not rendering the summary when it's expanded is still optional, since I think in some cases (eg, smaller objects), it still looks "good". Other than that I think it would be a good addition a simpler option to a custom renderer.

**Comment by philcockfield** [comment]
Thanks @xyc, that's awesome.  Ended up doing your approach this way that suited my purposes:

```typescript
interface INodeRendererOptions {
  depth: number;
  name: string;
  data: any;
  isNonenumerable: boolean;
  expanded: boolean;
}
function nodeRenderer(props: INodeRendererOptions) {
  const { depth, name, data, isNonenumerable } = props;
  if (depth === 0) {
    const rootData = Array.isArray(data) ? data : {}; // NB: Don't show preview of object on root.
    return <ObjectRootLabel name={name} data={rootData} />;
  } else {
    return (
      <ObjectLabel name={name} data={data} isNonenumerable={isNonenumerable} />
    );
  }
}

```

**Comment by xyc** [comment]
@CodyReichert Thanks for the help on that feature!
@philcockfield That looks good. Let me know if you want to close out this one.

**Comment by philcockfield** [comment]
Hey @xyc - good to close by me - thanks!
