### ISSUE TITLE
Remove usages of unsafe lifecycle methods

### ISSUE THREAD

**Issue by Hypnosphi** [storybookjs/react-inspector#47]
React team recently published a blogpost: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

TL;DR: `cWM`, `cWRP`, and `cWU` methods are considered unsafe for future async rendering and will be deprecated soon. The recommended way for open source maintainers to deal with it is to use [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) package and migrate to new `static getDerivedStateToProps` method

**Comment by xyc** [comment]
@Hypnosphi Thanks! `cWRP` is actually used alongside with legacy context API. I'm going to integrate the new Context API, and push out a new major version of react-inspector that only supports React 16.3.0 onwards.

**Comment by xyc** [comment]
Resolved in #68
