### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by rivertam** [storybookjs/react-inspector#48]
Hi there.

So I'm trying to display an `EventEmitter` from `eventemitter3`, which has an internal property `_events` of type `Events`. This internal property does not have a `constructor`, so I'm getting an error on [this line](https://github.com/xyc/react-inspector/blob/master/src/object/ObjectValue.js#L59). I'd make a PR, but I actually don't know what the solution should be.

**Comment by rivertam** [comment]
Looking more into it, it looks like it's supposed to be impossible for an object to exist without a constructor... Might this be a bug in V8 or something?

**Comment by rivertam** [comment]
Tried it in Firefox and got the same result. This is an object being passed back to me from an iframe, so that might be related? I'm quite confused.

**Comment by ndelangen** [comment]
`Object.create(null)` will create an object without any prototype, thus have no constructor.

**Comment by rivertam** [comment]
Yes, I've been doing a good amount of research on this today. This is valid behavior in JS, so it should not cause an error in this library. Still unsure how -- if at all -- react-inspector can get the object type, but maybe it can just output a placeholder for the name in this case.

**Comment by ndelangen** [comment]
Sure, 'Object' seems fine to me... Would you want to create a PR for it?
