### ISSUE TITLE
storybook is not building

### ISSUE THREAD

**Issue by johninvicara** [storybookjs/react-inspector#56]
I get an error after "npm install" and "npm run storybook":

	compiler.hooks.compilation.tap(
		               ^

TypeError: Cannot read property 'compilation' of undefined

Not a big deal, but thought it might be due to some dev tool updates.
I cloned into a new directory, and just did the usual "npm install".

**Comment by CodyReichert** [comment]
I couldn't immediately reproduce, works on a fresh install for me.

Sounds kind of like this: https://github.com/storybooks/storybook/issues/3313

Maybe try and make sure all the packages are the right version, it's not using any globally installed packages, etc. What version of node/npm?

**Comment by johninvicara** [comment]
OK, I have workarounds for anyone else who is affected.

When I do a 'git clone' and then just do 'npm run build', it fails with 
TypeError: resolveFrom.silent is not a function.

This is fixed by wiping node_modules and deleting package-lock.json and a new npm install.

The Storybook issue is related to the item @CodyReichert reported above.  I did an 'npm uninstall @storybook/react' and then installed the 4.0.0-alpha.10 version, and it is working now.

Thanks much for the pointer @CodyReichert !
