### ISSUE TITLE
FIX the CI (replace with CircleCI?)

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/react-inspector#59]
The CI seems to be broken, perhaps node version?

Perhaps we should switch to CircleCI if we're going to invest time into fixing it?

Any takers? Should be hard to setup at all.

**Comment by ndelangen** [comment]
@xyc could you connect CircleCI to the repo?

**Comment by ndelangen** [comment]
We should also add Chromatic on top of the storybook!

@xyc if you don't have time do do it? can we transfer this repo into an organisation so I can get administrator-right and do it for you?

**Comment by CodyReichert** [comment]
Build fixed in #60

**Comment by xyc** [comment]
@ndelangen @CodyReichert sorry just got to this. Just added circle CI. Please let me know if anything else is needed
