### ISSUE TITLE
Package contains ES2015 code

### ISSUE THREAD

**Issue by jamiewinder** [storybookjs/react-inspector#72]
I don't know if you consider this to be an issue or not, but the dist code for this package now includes ES2015+ code (as of v3.0.0). For example, `const` and `let`. I'm able to transpile this myself of course, but I find it rare to have to do so for a library so I'm not sure if it's intentional or not.

**Comment by xyc** [comment]
Thanks for reporting this issue. Looks that babel didn't transform `const` / `let`. Will take a look.
