### ISSUE TITLE
Add looser peer dep requirements for react and react-dom?

### ISSUE THREAD

**Issue by majapw** [storybookjs/react-inspector#79]
QQ: Would it be possible to loosen the react and react-dom peer dep restrictions to ^16.0.0 or are there explicit dependencies on react 16.8+ features in this library?

**Comment by xyc** [comment]
Please see the recommended versions section: https://github.com/storybookjs/react-inspector#install.  version `3.0.2`+ requires hooks support to work properly. If you are not using react 16.8+, you can stick with version `2.3.1`.

**Comment by majapw** [comment]
Unfortunately, I am not using this package directly, but rather a package I am using (Storybook) relies on it. Sounds like it has a hard dependency on 16.8 though. Thanks!

**Comment by ndelangen** [comment]
Storybook should work for React 15 and up?
