### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by jmikedupont2** [storybookjs/react-inspector#86]
The link in the project description is 404

http://xyc.github.io/react-inspector/

**Comment by xyc** [comment]
This happens when I moved the repo from my personal account @xyc to the @storybookjs org. @ndelangen Could you take a look at this? If you set me up for admin access to this repo, I can set up the github pages for this again.

**Comment by cefn** [comment]
The linked URL is still 404 https://xyc.github.io/react-inspector/

**Comment by ndelangen** [comment]
I changed it to the deployed storybook.
