### ISSUE TITLE
Upgrading storybook-chromatic version?

### ISSUE THREAD

**Issue by LostInBrittany** [storybookjs/react-inspector#97]
Hi!

I am using `react-inspector` via `@storybook/addon-actions` on an [OpenWC](https://open-wc.org/) project.

`react-inspector` has currently a dependency to `storybook-chromatic` 2.2.2, that itself has a dependency to an old version of `jsdom` that has a deprecated dependency to `left-pad`.

Would it be possible to upgrade to `storybook-chromatic` 3.1.0 that has upgraded the `jsdom` version dependency, or there is an important reason not to do it?

I can try a PR, if you don't mind...

**Comment by csimi** [comment]
Shuldn't this be a devDependency though?
Edit: yeah, there is a separate PR for that

**Comment by LostInBrittany** [comment]
Yeah, I have seem another PR doing that and I didn't want to overwrite it
